export const refundHistory = [
  {
    id: "cancel-pending",
    type: "취소",
    status: "취소 진행 중",
    completedAt: "",
    cash: null,
    points: null,
  },
  {
    id: "cancel-complete",
    type: "취소",
    status: "취소 완료",
    completedAt: "2026.09.11",
    cash: 89000,
    points: 1000,
  },
  {
    id: "refund-complete",
    type: "환불",
    status: "환불 완료",
    completedAt: "2026.09.10",
    cash: 89000,
    points: 1000,
  },
  {
    id: "exchange-complete",
    type: "교환",
    status: "교환 완료",
    completedAt: "2026.09.09",
    cash: null,
    points: null,
  },
].map((entry, index) => ({
  ...entry,
  fundingNumber: `FD260909-${String(index + 1).padStart(6, "0")}`,
  title: "프로젝트 명[진짜싹싹] 35,000Pa 초강력 흡입, 가볍게 끝내는 무선청소기",
  requestedAt: "2026.09.09",
  reason: entry.type === "교환" ? "상품 불량" : "단순 변심",
  product: "진짜싹싹 무선청소기",
  option: "화이트 / 기본 패키지",
  price: 90000,
  quantity: 1,
}));
